In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
thorino=cv2.imread("thorino.jpg")
graythorino=cv2.cvtColor(thorino, cv2.COLOR_BGR2GRAY)

In [27]:
def Sobel_filtering(gray):
    H,W=gray.shape
    
    sobely=np.array(((1,2,1),(0,0,0),(-1,-2,-1)),dtype=np.float32)
    sobelx=np.array(((1,0,-1),(2,0,-2),(1,0,-1)),dtype=np.float32)
    
    tmp=np.pad(gray,(1,1),'edge')
    
    Ix=np.zeros_like(gray,dtype=np.float32)
    Iy=np.zeros_like(gray,dtype=np.float32)
    
    for y in range(H):
        for x in range(W):
            Ix[y,x]=np.mean(tmp[y:y+3,x:x+3]*sobelx)
            Iy[y,x]=np.mean(tmp[y:y+3,x:x+3]*sobely)
            
    Ix2=Ix**2
    Iy2=Iy**2
    Ixy=Ix*Iy
    
    return Ix2,Iy2,Ixy

def corner_detect(gray,Ix2,Iy2,Ixy):
    H,W=gray.shape
    
    out=np.array((gray,gray,gray))
    out=np.transpose(out,(1,2,0))
    
    Hes=np.zeros((H,W))
    
    Hes=Ix2*Iy2-Ixy*Ixy
    th=np.max(Hes)*0.1
    corner=[]
    for y in range(H):
        for x in range(W):
            if Hes[y,x]==np.max(Hes[max(y-1,0):min(y+2,H),max(x-1,0):min(x+2,W)]) and Hes[y,x]>th:
                corner.append((y,x))
                
    for y,x in corner:
        out[max(y-1,0):min(y+2,H),max(x-1,0):min(x+2,W)]=[0,0,255] #わかりやすさのために周囲を赤くする
        
    return out.astype(np.uint8)

In [28]:
Ix2,Iy2,Ixy=Sobel_filtering(graythorino.copy())
ans1=corner_detect(graythorino.copy(),Ix2,Iy2,Ixy)
cv2.imwrite("ans1.jpg",ans1)

True

In [10]:
a=np.arange(4)
b=np.array((a,a,a))
np.where(b>2)
# np.transpose(b,(1,2,0))

(array([0, 1, 2]), array([3, 3, 3]))

In [14]:
np.where(b==2)

(array([0, 1, 2]), array([2, 2, 2]))

In [19]:
b[(1,3)]=100

In [20]:
b

array([[  0,   1,   2,   3],
       [  0,   1,   2, 100],
       [  0,   1,   2,   3]])